---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usherlock-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: usherlock:cluster-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "pods/exec", "namespaces", "services", "nodes", "daemonsets", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: usherlock:cluster-role-binding
subjects:
- kind: ServiceAccount
  name: usherlock-account
  namespace: default
roleRef:
 kind: ClusterRole
 name: usherlock:cluster-role
 apiGroup: rbac.authorization.k8s.io